### ISSUE TITLE
serialize

### ISSUE THREAD

**Issue by francescoagati** [olekscode/MLNeuralNetwork#1]
hi,
the state of the model can be serialized with ston or fuel?
thanks

**Comment by olekscode** [comment]
Hello!
Yes, it should be.
I can't tell you for sure, because I didn't use fuel that much, but a year ago I have implemented my own "serialization" (basically, it just stored the weights to a file and read them later) and people suggested that I use fuel for that. I think I did and it worked (but I don't remember).
So you can try.
And please let me know if it works for you

**Comment by francescoagati** [comment]
ok i  will try. thanks
